### ISSUE TITLE
Configure Cobbler profiles is not idempotent when a snippet is configured

### ISSUE THREAD

**Issue by btravouillon** [mila-iqia/ansible-role-cobbler#14]
When `cobbler_profiles[*].snippets` is defined, any run of the task returns an mtime change.

Example with this inventory:
```
cobbler_profiles:
  # Compute nodes profiles
  - name: cn-a
    properties:
      distro: ubuntu-18.04
      autoinstall: debian.seed

  - name: cn-b
    properties:
      distro: ubuntu-18.04
      autoinstall: debian.seed

  - name: cn-c
    properties:
      distro: ubuntu-18.04
      autoinstall: debian.seed

  - name: cn-f
    properties:
      distro: ubuntu-18.04
      autoinstall: debian.seed
    snippets:
      - name: partition
        content: |
          # foo

  - name: cn-g
    properties:
      distro: ubuntu-18.04
      autoinstall: debian.seed
    snippets:
      - name: partition
        content: |
          # bar
```

```
TASK [cobbler : Configure Cobbler profiles] **********************************************************************************************
ok: [cobbler -> localhost] => (item=cn-a)
ok: [cobbler -> localhost] => (item=cn-b)
ok: [cobbler -> localhost] => (item=cn-c)
--- before
+++ after
@@ -36,7 +36,7 @@
     "menu": "",
     "mgmt_classes": "<<inherit>>",
     "mgmt_parameters": "<<inherit>>",
-    "mtime": 1682822160.945022,
+    "mtime": 1682866076.19273,
     "name": "cn-f",
     "name_servers": [],
     "name_servers_search": [],

changed: [cobbler -> localhost] => (item=cn-f)
--- before
+++ after
@@ -65,7 +65,7 @@
     "menu": "",
     "mgmt_classes": "<<inherit>>",
     "mgmt_parameters": "<<inherit>>",
-    "mtime": 1682822164.1639857,
+    "mtime": 1682866079.39695,
     "name": "cn-g",
     "name_servers": [],
     "name_servers_search": [],

changed: [cobbler -> localhost] => (item=cn-g)
--- before
+++ after
@@ -36,7 +36,7 @@
     "menu": "",
     "mgmt_classes": "<<inherit>>",
     "mgmt_parameters": "<<inherit>>",
-    "mtime": 1682822179.0738401,
+    "mtime": 1682866094.4046662,
     "name": "cn-h",
     "name_servers": [],
     "name_servers_search": [],

changed: [cobbler -> localhost] => (item=cn-h)
```
